### ISSUE TITLE
Redirection even when the user interacts with the app

### ISSUE THREAD

**Issue by inossan-dev** [SankethBK/local_session_timeout#5]
Hi!
Could you help me please?
**invalidateSessionForUserInactiviity** is triggered even when there is a user activity session.

**Comment by SankethBK** [comment]
Hi, can you please post your code for better understanding of the issue

**Comment by inossan-dev** [comment]
I finally solved the problem.
I should specify the **userActivityDebounceDuration** attribute to a shorter time, in my use case
Thanks a lot!

**Comment by sritharanMobileDev** [comment]
> I finally solved the problem. I should specify the **userActivityDebounceDuration** attribute to a shorter time, in my use case Thanks a lot!

I'm Also facing the same issue. what you fixed in your code.

Here is my sample code.


After continuously  using of 10 minutes, app gets logged out.


final sessionConfig = SessionConfig(
    invalidateSessionForAppLostFocus: Duration(
        minutes:10),
    invalidateSessionForUserInactivity: Duration(
        minutes: 10);

sessionConfig.stream.listen((SessionTimeoutState timeoutEvent) {
  if (timeoutEvent == SessionTimeoutState.userInactivityTimeout ||
      timeoutEvent == SessionTimeoutState.appFocusTimeout) {
   // redirect to login screen
  }
});

return SessionTimeoutManager(
    userActivityDebounceDuration: const Duration(seconds: 1),
    sessionConfig: sessionConfig,
    sessionStateStream: sessionStateStream.stream,
    child: Scaffold(appBar: _appBar(), body: _body()));
